online_global_map_builder:
  ros__parameters:
    submap_grid_topic: /submap_manager/submap_grids
    optimized_submap_pose_topic: /culvert_pgo_node/optimized_submap_poses
    dirty_submap_topic: /culvert_pgo_node/dirty_submap_list
    map_topic: /map
    map_frame: map

    map_publish_rate: 1.0
    include_active_submap: true

    hit_score: 4
    miss_score: 1
    occupied_threshold: 2
    free_threshold: -1
    robot_clear_radius: 0.35
